Resources:
  GlueJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: myGlueJob
	  Role: !GetAtt glueServiceRoleSushil.Arn
	  Command:
	     Name: glueETL
		 ScriptLocation: s3://mycodepipelinebucketsushil/script/glue_script.py
	  DefaultArguments:
	   "--tempDir": "s3:://mycodepipelinebucketsushil/temp/"
	   GlueVersion: "2.0"
	   WorkerType: G.1X
	   NumberofWorkers: 2
	   
	   
	glueServiceRoleSushil:
	   Type: AWS::IAM:Role
	   Properties:
        RoleName: !Sub "$(AWS::StackName)-myRoleForGlue"
		AssumeRolePolicyDocument:
		Version: "2012-10-17"
        Statement:
         -Effect: "Allow"
          Principal: 
                Service: glue.amazonaws.com
          Action: sts:AssumeRole
		ManagedPolicyArns:
		  -arn:aws:iam::aws:policy/AmazonS3FullAccess
		  -arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
		  
		  
